/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [35.39KB] > /Users/kiyotaka/Desktop/model/scene-transformed.glb [362.22KB] (-924%)
Author: WhatIsLove (https://sketchfab.com/vladgutu11)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-16-plus-c1719ed762a7412d933f3ddef0ce2929
Title: Iphone 16 Plus
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Screen_Glass} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Antenna} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Glass_Camera_Logo} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Back_Cover} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Screen_Rim} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Grill_USB} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Camera_Pixel_Glass_002} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Camera_Pixel__002} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.Plastic} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.Rim_Buttons} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.Flash_Glass_002} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.Flash_002} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.Screen_BG} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.Screw} position={[0, 0, 0.17]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
